### ISSUE TITLE
Замечания по работе

### ISSUE THREAD

**Issue by AndriiLitvin** [kurapov/kurapov.github.io#1]
Визуально:
1) Картинка меньшей ширины
2) На картинке нет border-radius как на превью https://raw.githubusercontent.com/goit-fe/markup_fe2o/master/lesson_01/homework1.png
3) Сделай чуть светлее и больший box-shadow
4)Подчеркивание под каждым блоком тоже сделать светлее

Код:
1)Название классов должно быть говорящее, чтоб без контента программист мог понять что там выводить.
2)Перенос строки и отступы желательно делать через css.

**Comment by kurapov** [comment]
спасибо, выполнено

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
